spring.application.name=reminder

spring.datasource.url=jdbc:postgresql://dpg-d767s6paae7s73bvetj0-a.oregon-postgres.render.com:5432/reminder_5loq
spring.datasource.username=reminder_5loq_user
spring.datasource.password=PMGxLPV9sGw29Bd0qT2UCA7iCMcZxBwy
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Email settings (configure your Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=n81430773@gmail.com
spring.mail.password=kgqb rpon ldlv lldf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=n81430773@gmail.com
spring.mail.properties.mail.smtp.ssl.trust=*

spring.main.allow-bean-definition-overriding=true

server.port = 8082

firebase.config=${FIREBASE_CONFIG}
